### ISSUE TITLE
Ritual Favor Outcomes

### ISSUE THREAD

**Issue by bunnies1230** [xIdentified/Devotions#11]
In the rituals.yml, there's a config for setting the amount of favor per ritual, but it might be hard coded and ignores that config completely? Tested on my server and successful rituals gave 25 and failed ones penalized 15, which seems to be in line with the code here? [{1}](https://github.com/xIdentified/Devotions/blob/252b9a4865fb2597aae351965027c6dcce2b2192/src/main/java/me/xidentified/devotions/rituals/Ritual.java#L162) [{2}](https://github.com/xIdentified/Devotions/blob/252b9a4865fb2597aae351965027c6dcce2b2192/src/main/java/me/xidentified/devotions/rituals/Ritual.java#L169)

I don't know java terribly well so maybe that's not it, but I figured I'd make an issue about the config not working correctly.

On that note, if you fix this, is it possible to allow for the favor config in rituals.yml to use negatives or accept 0?

Thanks!

**Comment by xIdentified** [comment]
Thank you for pointing that out, meant to do that first time around setting up rituals lol. Fixed, also I tried it and you can use negatives or zero but the message looks weird so I'll have to mess with it tomorrow.
