### ISSUE TITLE
Idea: Toggle to consume/not consume ritual items

### ISSUE THREAD

**Issue by bunnies1230** [xIdentified/Devotions#13]
As I've been playing around with rituals, I thought it might add another layer of customization to have a per-ritual option to consume (or not consume) the triggering item and/or the gathered items.

For example, this ritual would not consume the bucket used to start the ritual, but would consume the cod used to finish it.

>   rain_dance:
    display_name: "Ritual of Rain"
    description: "Summons Rain and Storms \nRequirements: Clear Sky, 150+ Favor"
    favor: -10
    item: "VANILLA:BUCKET"
       _**consume: false**_
    conditions:
       weather: "CLEAR"
     objectives:
       - type: "GATHERING"
         description: "Bring 20 raw cod to the shrine"
         target: "COD"
         count: 20
         **_consume: true_**
    outcome-command:
      - "weather world storm 1200"

Both would be cool to play around with, but if the first one is a lot of work (consuming the triggering item), I'd much rather have the latter (consuming the gathered items).

**Comment by xIdentified** [comment]
The first one was easier to implement for now, might do the other one later but not a priority. Next update you can add 'consume-item' it will be true by default. :)
