### ISSUE TITLE
Player losing Favor, while being offline

### ISSUE THREAD

**Issue by ChristopherPS96** [xIdentified/Devotions#5]
Servertype: JAVA PAPER SERVER 1.20.1
Plugin: Latest Version - v1.1-beta.1

We have an 24/7 always running server, where we installed the plugin.

My user base has reported back to me, that they lose Favor while being offline.
I don't think that this should be the case, or at least be changeable in the configs.

If more information is needed, I'm happy to help.

**Comment by xIdentified** [comment]
I was able to add a config option, will be in the next update :)
